/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/kitchen/account`; params?: Router.UnknownInputParams; } | { pathname: `/kitchen`; params?: Router.UnknownInputParams; } | { pathname: `/waiter/account`; params?: Router.UnknownInputParams; } | { pathname: `/waiter`; params?: Router.UnknownInputParams; } | { pathname: `/waiter/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/waiter/session/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/kitchen/account`; params?: Router.UnknownOutputParams; } | { pathname: `/kitchen`; params?: Router.UnknownOutputParams; } | { pathname: `/waiter/account`; params?: Router.UnknownOutputParams; } | { pathname: `/waiter`; params?: Router.UnknownOutputParams; } | { pathname: `/waiter/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/waiter/session/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/kitchen/account${`?${string}` | `#${string}` | ''}` | `/kitchen${`?${string}` | `#${string}` | ''}` | `/waiter/account${`?${string}` | `#${string}` | ''}` | `/waiter${`?${string}` | `#${string}` | ''}` | `/waiter/notifications${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/kitchen/account`; params?: Router.UnknownInputParams; } | { pathname: `/kitchen`; params?: Router.UnknownInputParams; } | { pathname: `/waiter/account`; params?: Router.UnknownInputParams; } | { pathname: `/waiter`; params?: Router.UnknownInputParams; } | { pathname: `/waiter/notifications`; params?: Router.UnknownInputParams; } | `/waiter/session/${Router.SingleRoutePart<T>}` | { pathname: `/waiter/session/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
